[project]
name = "FunPayAPI"
version = "0.1.0"
description = "A Python wrapper for the FunPay API."
requires-python = ">=3.8"
dependencies = [
    "loguru",
    "primp",
    "beautifulsoup4",
    "lxml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
